project_name: tfui

builds:
  - main: ./cmd/tfui
    binary: tfui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: SayYoungMan
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_TOKEN }}"
    homepage: https://github.com/SayYoungMan/tfui
    description: Interactive TUI for performing Terraform workflows
    license: MIT
    install: |
      bin.install "tfui"

scoops:
  - repository:
      owner: SayYoungMan
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_TOKEN }}"
    homepage: https://github.com/SayYoungMan/tfui
    description: Interactive TUI for performing Terraform workflows
    license: MIT

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
